/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DebugPanel: typeof import('./src/components/DebugPanel.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ListCard: typeof import('./src/components/ListCard.vue')['default']
    NewItemDialog: typeof import('./src/components/NewItemDialog.vue')['default']
    PantryItemCard: typeof import('./src/components/PantryItemCard.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
