/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/despensa': RouteRecordInfo<'/despensa', '/despensa', Record<never, never>, Record<never, never>>,
    '/editar-perfil': RouteRecordInfo<'/editar-perfil', '/editar-perfil', Record<never, never>, Record<never, never>>,
    '/list': RouteRecordInfo<'/list', '/list', Record<never, never>, Record<never, never>>,
    '/listas': RouteRecordInfo<'/listas', '/listas', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mi-lista': RouteRecordInfo<'/mi-lista', '/mi-lista', Record<never, never>, Record<never, never>>,
    '/perfil': RouteRecordInfo<'/perfil', '/perfil', Record<never, never>, Record<never, never>>,
    '/productos': RouteRecordInfo<'/productos', '/productos', Record<never, never>, Record<never, never>>,
    '/registro': RouteRecordInfo<'/registro', '/registro', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/despensa.vue': {
      routes: '/despensa'
      views: never
    }
    'src/pages/editar-perfil.vue': {
      routes: '/editar-perfil'
      views: never
    }
    'src/pages/list.vue': {
      routes: '/list'
      views: never
    }
    'src/pages/listas.vue': {
      routes: '/listas'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/mi-lista.vue': {
      routes: '/mi-lista'
      views: never
    }
    'src/pages/perfil.vue': {
      routes: '/perfil'
      views: never
    }
    'src/pages/productos.vue': {
      routes: '/productos'
      views: never
    }
    'src/pages/registro.vue': {
      routes: '/registro'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
